---
hero_image: images/banner.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Moonhack Python 2017
description: Moonhack Python 2017!
original_url: https://codeclubprojects.org/en-GB/python/moonhack-python
interests: ''
technologies: python
site_areas: codeclub, python
steps:
- title: Introduction
- title: Import the Starter Code
- title: Displaying a List
- title: 'Challenge: More Items'
- title: Interacting with the User
- title: 'Organizing the User Input '
- title: 'Evaluating the User Input '
- title: 'Will you make it to the Moon Base? '
- title: 'Challenge: Wrong Item'

